# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mhacks12' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for mhacks12
  pod 'Firebase/Core'
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Email'
  pod 'Firebase/Database'
  pod 'Kingfisher', '~> 5.0'
  pod 'ImageSlideshow', '~> 1.8.1'
  pod "ImageSlideshow/Kingfisher"


  target 'mhacks12Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'mhacks12UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
